### ISSUE TITLE
Analyze nearinfrared pictures

### ISSUE THREAD

**Issue by FlorianRocher** [TiagoOlivoto/pliman#13]
Hi !

Thanks for this nice package.
Do you know how I should proceed to use it to measure symptom area from pictures obtained from a Bio-Rad ChemiDoc MP Imager with nearinfrared settings that are black and white? I have troubles using the measure_disease function on those.
![po-pi-b4-l2](https://github.com/TiagoOlivoto/pliman/assets/91314378/0e9b0c7e-5468-472f-9bc6-696047c42b54)

Thanks for your help !

Florian Rocher

**Comment by TiagoOlivoto** [comment]
``` r
library(pliman)
#> |==========================================================|
#> | Tools for Plant Image Analysis (pliman 2.1.0)            |
#> | Author: Tiago Olivoto                                    |
#> | Type `citation('pliman')` to know how to cite pliman     |
#> | Visit 'http://bit.ly/pkg_pliman' for a complete tutorial |
#> |==========================================================|
set_wd_here()
img <- image_import("nir.jpg")


# index to segment
ind <- image_index(img, index = "R")
```

![image](https://github.com/TiagoOlivoto/pliman/assets/34458429/85bb6a8e-7e43-4aab-9822-4c39d24debbb)
plot(ind, type = "density")

``` r
# Segment the leaf
seg <- 
  image_segment(img, 
                index = "R",
                # threshold = 0.1, # optionally set the threshold
                invert = TRUE,
                filter = 20) # remove noise
```
![image](https://github.com/TiagoOlivoto/pliman/assets/34458429/bd2c0a21-fbe6-4888-9192-f2667bff1184)

``` r
# Make another segmentation to isolate the diseased tissue
# Now, segment the disease
image_segment(seg, 
              index = "R",
              # threshold = 0.1, # optionally set the threshold
              invert = TRUE)
```
![image](https://github.com/TiagoOlivoto/pliman/assets/34458429/febfe019-9f8d-4c4b-be98-8578e478bb43)

``` r
# Combine the approaches by declaring one index to segment the background
# and another index to segment the diseased tissue

sev <- 
measure_disease(img,
                index_lb = "B",
                index_dh = "B",
                invert = c(TRUE, TRUE),
                col_lesions = "red",
                show_original = FALSE,
                filter = 20)
```
![image](https://github.com/TiagoOlivoto/pliman/assets/34458429/b0639db6-1ddd-4c2c-8d04-11b5da49e416)

``` r
healthy symptomatic
1 96.35847    3.641526
```

Hope it helps!


<sup>Created on 2024-03-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by FlorianRocher** [comment]
Hi, 

Thanks for your help. It has been helpful!
When I run the image_index(img, index="R") line I obtain the following picture.
![Capture](https://github.com/TiagoOlivoto/pliman/assets/91314378/08018393-184a-4f10-90f4-941acbfc9577)
Do you know why I don't have the yellow background as you ?
And another question: All the steps of index and segment the pictures are done to check if we will able to correctly asses the disease area with the chosen index right ?

Thanks and have a nice day !

Florian Rocher

**Comment by TiagoOlivoto** [comment]
Hi,
Try install pliman from github.. you probably have an older version than me.
Yes, all steps before measure_disease() are just to find appropriate indexes
I'm closing this now
Best
