### ISSUE TITLE
No mosaic_analyze funcion 

### ISSUE THREAD

**Issue by Yanjie-Li** [TiagoOlivoto/pliman#14]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem

```r
library(pliman)
> res <- mosaic_analyze(fa,
+                  nrow = 3,  # use 6 if you want to analyze in a single block
+                  ncol = 15,
+                  buffer_row = -0.15,
+                  buffer_col = -0.05,
+                  segment_plot = TRUE,
+                  segment_index = "NDVI", 
+                  plot_index = c("NDVI", "EVI", "NDRE"), 
+                  summarize_fun = c("min", "mean", "max"),
+                  attribute = "coverage")
#Error in mosaic_analyze(fa, nrow = 3, ncol = 15, buffer_row = -0.15, buffer_col = -0.05,  : 
 # 没有"mosaic_analyze"这个函数
```

**Comment by TiagoOlivoto** [comment]
Hi @Yanjie-Li 

Please, ensure you have the development version of pliman installed with `pak::pkg_install("TiagoOlivoto/pliman")`
