### ISSUE TITLE
ANALYZING ORTHOMOSAICS IN R WITH PLIMAN PACKAGE -FUNCTION analyze_mosaic is not present in the package

### ISSUE THREAD

**Issue by mfm2174** [TiagoOlivoto/pliman#8]
Good morning,

I was watching your video: https://www.youtube.com/watch?v=zROvQKKRPqA (ANALYZING ORTHOMOSAICS IN R WITH PLIMAN PACKAGE).

Finally I could download the package in LINUX, unfortunately I don't see the function analyze_mosaic included. The following mosaic functions are installed: mosaic_crop; mosaic_export; mosaic_index; mosaic_input; mosaic_to_pliman; mosaic_to_rgb; mosaic_view and mosaic_plot.

Can you help me please?

**Comment by TiagoOlivoto** [comment]
Hi, 
It seems that you do not have the dev version installed. Are you sure that devtools::install_github("TiagoOlivoto/pliman") was successfully installed?

If so, try restarting the R section.

"Issues" are not the appropriate local to get help, but a local to report clear bugs in the code. You can email me at tiagoolivoto@gmail.com if you have any questions that are not related to bug reports.
Best
