### ISSUE TITLE
mosaic_analyze function dissapeared from PLIMAN package overnight

### ISSUE THREAD

**Issue by mfm2174** [TiagoOlivoto/pliman#9]
In R when you search for the function it's not appearing anymore (Please see the image I uploaded). From one day to another the function dissapeared.  I just discovered that when I tried to run the following script:

> res_pot<-mosaic_analyze(pot,
+                         r=1,g=2,b=3,
+                         nrow=9,
+                         ncol=16,
+                         buffer_row = -0.15, # 15% não é considerado entre filas
+                         buffer_col = -0.05, #  5% não é considerado entre colunas
+                         plot_index = c("GLI","NGRDI","VARI","BGI"),
+                         summarize_fun = c("mean","stdev"),
+                         plot=FALSE)

Error in mosaic_analyze(pot, r = 1, g = 2, b = 3, nrow = 9, ncol = 16,  : 
  não foi possível encontrar a função "mosaic_analyze"
![image (1)](https://github.com/TiagoOlivoto/pliman/assets/149332327/44418c87-8eec-4070-b7b1-b898e6373334)

**Comment by TiagoOlivoto** [comment]
mosaic_analyze() is working fine
![image](https://github.com/TiagoOlivoto/pliman/assets/34458429/85d4b2ed-5e0a-4801-98d0-be3875a01914)

Please, ensure you have the development version installed, following [this instruction](https://github.com/TiagoOlivoto/pliman?tab=readme-ov-file#installation
). That function is not on CRAN
